package com.ikkong.system.model;

import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;
import java.math.BigDecimal;
import java.util.Date;

import org.beetl.sql.core.annotatoin.AutoID;

/**
 * Generated by Blade.
 * 2017-11-07 18:07:53
 */
@Table(name = "glpt_building_owner")
@BindID(name = "id")
@SuppressWarnings("serial")
public class BuildingOwner extends BaseModel {
    	private Long id; //id
    	private String idno; //身份证号码
    	private String legalperson; //法人
    	private String name; //公司名称
    	private String ownertype; //业主类型（个人/企业）
    	private String phone; //手机号码
    	private String floors;//拥有的楼层 
    	private Long buildingid;
    	private Date addtime; //添加时间
    	private Integer adduserid; //添加用户ID
    	private String addusername; //添加用户名
    	private Integer modifyuserid; //修改用户id
    	private String modifyusername; //修改用户
    	private Date modifytime; //修改时间
    	private Integer status; //status
    	private Integer version=1;
    	private Long enterpriseid; //关联的企业id

    	@AutoID
    	public Long getId() {
    		return id;
    	}

    	public void setId(Long id) {
    		this.id = id;
    	}

    	public Integer getModifyuserid() {
    		return modifyuserid;
    	}

    	public void setModifyuserid(Integer modifyuserid) {
    		this.modifyuserid = modifyuserid;
    	}

    	public Integer getStatus() {
    		return status;
    	}

    	public void setStatus(Integer status) {
    		this.status = status;
    	}

    	public Integer getVersion() {
    		return version;
    	}

    	public void setVersion(Integer version) {
    		this.version = version;
    	}

    	public Integer getAdduserid() {
    		return adduserid;
    	}

    	public void setAdduserid(Integer adduserid) {
    		this.adduserid = adduserid;
    	}

    	public String getAddusername() {
    		return addusername;
    	}

    	public void setAddusername(String addusername) {
    		this.addusername = addusername;
    	}

    	public Long getEnterpriseid() {
    		return enterpriseid;
    	}

    	public void setEnterpriseid(Long enterpriseid) {
    		this.enterpriseid = enterpriseid;
    	}

    	public String getIdno() {
    		return idno;
    	}

    	public void setIdno(String idno) {
    		this.idno = idno;
    	}

    	public String getLegalperson() {
    		return legalperson;
    	}

    	public void setLegalperson(String legalperson) {
    		this.legalperson = legalperson;
    	}

    	public String getModifyusername() {
    		return modifyusername;
    	}

    	public void setModifyusername(String modifyusername) {
    		this.modifyusername = modifyusername;
    	}

    	public String getName() {
    		return name;
    	}

    	public void setName(String name) {
    		this.name = name;
    	}

    	public String getOwnertype() {
    		return ownertype;
    	}

    	public void setOwnertype(String ownertype) {
    		this.ownertype = ownertype;
    	}

    	public String getPhone() {
    		return phone;
    	}

    	public void setPhone(String phone) {
    		this.phone = phone;
    	}

    	public Date getAddtime() {
    		return addtime;
    	}

    	public void setAddtime(Date addtime) {
    		this.addtime = addtime;
    	}

    	public Date getModifytime() {
    		return modifytime;
    	}

    	public void setModifytime(Date modifytime) {
    		this.modifytime = modifytime;
    	}

		public String getFloors() {
			return floors;
		}

		public void setFloors(String floors) {
			this.floors = floors;
		}

		public Long getBuildingid() {
			return buildingid;
		}

		public void setBuildingid(Long buildingid) {
			this.buildingid = buildingid;
		}

}
