package com.ikkong.system.model;

import java.math.BigDecimal;
import java.util.Date;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

/**
 * Generated by Blade.
 * 2017-11-07 18:07:53
 */
@Table(name = "glpt_building")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Building extends BaseModel {
	private Long id; //id
	private Integer floorcount; //楼宇层数
	private Integer modifyuserid; //修改用户id
	private Integer status; //状态
	private Integer version=0;
	private Integer adduserid; //添加用户ID
	private String addusername; //添加用户名
	private Long areaid; //归属片区
	private String buildname; //楼宇名称
	private Float coveredarea; //总建筑面积
	private Float eachcoveredarea; //每层建筑面积
	private BigDecimal latitude; //纬度
	private BigDecimal longitude; //经度
	private String maparea; //地图多边形区域
	private String modifyusername; //修改用户
	private Date addtime; //添加时间
	private Date modifytime; //修改时间

	@AutoID
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Integer getFloorcount() {
		return floorcount;
	}

	public void setFloorcount(Integer floorcount) {
		this.floorcount = floorcount;
	}

	public Integer getModifyuserid() {
		return modifyuserid;
	}

	public void setModifyuserid(Integer modifyuserid) {
		this.modifyuserid = modifyuserid;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getVersion() {
		return version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Integer getAdduserid() {
		return adduserid;
	}

	public void setAdduserid(Integer adduserid) {
		this.adduserid = adduserid;
	}

	public String getAddusername() {
		return addusername;
	}

	public void setAddusername(String addusername) {
		this.addusername = addusername;
	}

	public Long getAreaid() {
		return areaid;
	}

	public void setAreaid(Long areaid) {
		this.areaid = areaid;
	}

	public String getBuildname() {
		return buildname;
	}

	public void setBuildname(String buildname) {
		this.buildname = buildname;
	}

	public Float getCoveredarea() {
		return coveredarea;
	}

	public void setCoveredarea(Float coveredarea) {
		this.coveredarea = coveredarea;
	}

	public Float getEachcoveredarea() {
		return eachcoveredarea;
	}

	public void setEachcoveredarea(Float eachcoveredarea) {
		this.eachcoveredarea = eachcoveredarea;
	}

	public BigDecimal getLatitude() {
		return latitude;
	}

	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	public BigDecimal getLongitude() {
		return longitude;
	}

	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	public String getMaparea() {
		return maparea;
	}

	public void setMaparea(String maparea) {
		this.maparea = maparea;
	}

	public String getModifyusername() {
		return modifyusername;
	}

	public void setModifyusername(String modifyusername) {
		this.modifyusername = modifyusername;
	}

	public Date getAddtime() {
		return addtime;
	}

	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	public Date getModifytime() {
		return modifytime;
	}

	public void setModifytime(Date modifytime) {
		this.modifytime = modifytime;
	}

}
