package com.ikkong.system.model;

import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

import java.math.BigDecimal;
import java.util.Date;

import org.beetl.sql.core.annotatoin.AutoID;
/**
 * Generated by Blade.
 * 2017-11-07 18:07:53
 */
@Table(name = "glpt_enterprises_certification")
@BindID(name = "id")
@SuppressWarnings("serial")
public class EnterprisesCertification extends BaseModel {
    	private Long id; //id
    	private Integer modifyuserid; //修改用户id
    	private Integer status; //status
    	private Integer version=0;
    	private Long adduserid; //添加用户ID
    	private String addusername; //添加用户名
    	private String authdate; //认证时间
    	private String authname; //认证名称
    	private String authorg; //认证机构
    	private Long enterpriseid; //enterpriseid
    	private String expirationdate; //有效期限
    	private String modifyusername; //修改用户
    	private Date addtime; //添加时间
    	private Date modifytime; //修改时间

    	@AutoID
    	public Long getId() {
    		return id;
    	}

    	public void setId(Long id) {
    		this.id = id;
    	}

    	public Integer getModifyuserid() {
    		return modifyuserid;
    	}

    	public void setModifyuserid(Integer modifyuserid) {
    		this.modifyuserid = modifyuserid;
    	}

    	public Integer getStatus() {
    		return status;
    	}

    	public void setStatus(Integer status) {
    		this.status = status;
    	}

    	public Integer getVersion() {
    		return version;
    	}

    	public void setVersion(Integer version) {
    		this.version = version;
    	}

    	public Long getAdduserid() {
    		return adduserid;
    	}

    	public void setAdduserid(Long adduserid) {
    		this.adduserid = adduserid;
    	}

    	public String getAddusername() {
    		return addusername;
    	}

    	public void setAddusername(String addusername) {
    		this.addusername = addusername;
    	}

    	public String getAuthdate() {
    		return authdate;
    	}

    	public void setAuthdate(String authdate) {
    		this.authdate = authdate;
    	}

    	public String getAuthname() {
    		return authname;
    	}

    	public void setAuthname(String authname) {
    		this.authname = authname;
    	}

    	public String getAuthorg() {
    		return authorg;
    	}

    	public void setAuthorg(String authorg) {
    		this.authorg = authorg;
    	}

    	public Long getEnterpriseid() {
    		return enterpriseid;
    	}

    	public void setEnterpriseid(Long enterpriseid) {
    		this.enterpriseid = enterpriseid;
    	}

    	public String getExpirationdate() {
    		return expirationdate;
    	}

    	public void setExpirationdate(String expirationdate) {
    		this.expirationdate = expirationdate;
    	}

    	public String getModifyusername() {
    		return modifyusername;
    	}

    	public void setModifyusername(String modifyusername) {
    		this.modifyusername = modifyusername;
    	}

    	public Date getAddtime() {
    		return addtime;
    	}

    	public void setAddtime(Date addtime) {
    		this.addtime = addtime;
    	}

    	public Date getModifytime() {
    		return modifytime;
    	}

    	public void setModifytime(Date modifytime) {
    		this.modifytime = modifytime;
    	}

}
