package com.ikkong.system.model;

import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

import java.math.BigDecimal;
import java.util.Date;

import org.beetl.sql.core.annotatoin.AutoID;
/**
 * Generated by Blade.
 * 2017-11-07 18:07:53
 */
@Table(name = "glpt_enterprise_product")
@BindID(name = "id")
@SuppressWarnings("serial")
public class EnterpriseProduct extends BaseModel {
    	private Long id; //id
    	private Integer modifyuserid; //修改用户id
    	private Integer status; //status
    	private Integer version=0;
    	private Long adduserid; //添加用户ID
    	private String addusername; //添加用户名
    	private Long enterpriseid; //enterpriseid
    	private String materials; //主要原材料
    	private String modifyusername; //修改用户
    	private String output; //年产量
    	private String product; //品种
    	private String recommended; //入选工业产品推荐使用目录
    	private String trademark; //获名牌、驰名商标情况（国家、省、市级及授予时间）
    	private Date addtime; //添加时间
    	private Date modifytime; //修改时间

    	@AutoID
    	public Long getId() {
    		return id;
    	}

    	public void setId(Long id) {
    		this.id = id;
    	}

    	public Integer getModifyuserid() {
    		return modifyuserid;
    	}

    	public void setModifyuserid(Integer modifyuserid) {
    		this.modifyuserid = modifyuserid;
    	}

    	public Integer getStatus() {
    		return status;
    	}

    	public void setStatus(Integer status) {
    		this.status = status;
    	}

    	public Integer getVersion() {
    		return version;
    	}

    	public void setVersion(Integer version) {
    		this.version = version;
    	}

    	public Long getAdduserid() {
    		return adduserid;
    	}

    	public void setAdduserid(Long adduserid) {
    		this.adduserid = adduserid;
    	}

    	public String getAddusername() {
    		return addusername;
    	}

    	public void setAddusername(String addusername) {
    		this.addusername = addusername;
    	}

    	public Long getEnterpriseid() {
    		return enterpriseid;
    	}

    	public void setEnterpriseid(Long enterpriseid) {
    		this.enterpriseid = enterpriseid;
    	}

    	public String getMaterials() {
    		return materials;
    	}

    	public void setMaterials(String materials) {
    		this.materials = materials;
    	}

    	public String getModifyusername() {
    		return modifyusername;
    	}

    	public void setModifyusername(String modifyusername) {
    		this.modifyusername = modifyusername;
    	}

    	public String getOutput() {
    		return output;
    	}

    	public void setOutput(String output) {
    		this.output = output;
    	}

    	public String getProduct() {
    		return product;
    	}

    	public void setProduct(String product) {
    		this.product = product;
    	}

    	public String getRecommended() {
    		return recommended;
    	}

    	public void setRecommended(String recommended) {
    		this.recommended = recommended;
    	}

    	public String getTrademark() {
    		return trademark;
    	}

    	public void setTrademark(String trademark) {
    		this.trademark = trademark;
    	}

    	public Date getAddtime() {
    		return addtime;
    	}

    	public void setAddtime(Date addtime) {
    		this.addtime = addtime;
    	}

    	public Date getModifytime() {
    		return modifytime;
    	}

    	public void setModifytime(Date modifytime) {
    		this.modifytime = modifytime;
    	}

}
