package com.ikkong.system.model;

import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

import java.math.BigDecimal;
import java.util.Date;

import org.beetl.sql.core.annotatoin.AutoID;
/**
 * Generated by Blade.
 * 2017-11-07 18:07:53
 */
@Table(name = "glpt_enterprises_management")
@BindID(name = "id")
@SuppressWarnings("serial")
public class EnterprisesManagement extends BaseModel {
    	private Integer id; //ID
    	private Integer modifyuserid; //修改用户id
    	private Integer status; //status
    	private Integer taxyear; //缴税年度
    	private Integer version=0;
    	private Long adduserid; //添加用户ID
    	private String addusername; //添加用户名
    	private String annualtotal; //年度上缴税收年度总额（元）
    	private String enterpriseid; //关联的企业id
    	private String localtax; //地税（元）
    	private String modifyusername; //修改用户
    	private String statetax; //国税（元）
    	private String totleinput; //年度营业收入总额（万元）
    	private String totleoutput; //年度产值总额（万元）
    	private Date addtime; //添加时间
    	private Date modifytime; //修改时间
    	private String marketrate; //年度主要产品市场占有率
    	private String profitrate; //年度企业利润率
    	private String localtaxorg; //地税登记机关
    	private String statetaxorg; //国税登记机关

		@AutoID
    	public Integer getId() {
			return id;
		}

		public void setId(Integer id) {
			this.id = id;
		}


    	public Integer getModifyuserid() {
    		return modifyuserid;
    	}

    	public void setModifyuserid(Integer modifyuserid) {
    		this.modifyuserid = modifyuserid;
    	}

    	public Integer getStatus() {
    		return status;
    	}

    	public void setStatus(Integer status) {
    		this.status = status;
    	}

    	public Integer getTaxyear() {
    		return taxyear;
    	}

    	public void setTaxyear(Integer taxyear) {
    		this.taxyear = taxyear;
    	}

    	public Integer getVersion() {
    		return version;
    	}

    	public void setVersion(Integer version) {
    		this.version = version;
    	}

    	public Long getAdduserid() {
    		return adduserid;
    	}

    	public void setAdduserid(Long adduserid) {
    		this.adduserid = adduserid;
    	}

    	public String getAddusername() {
    		return addusername;
    	}

    	public void setAddusername(String addusername) {
    		this.addusername = addusername;
    	}

    	public String getAnnualtotal() {
    		return annualtotal;
    	}

    	public void setAnnualtotal(String annualtotal) {
    		this.annualtotal = annualtotal;
    	}

    	public String getEnterpriseid() {
    		return enterpriseid;
    	}

    	public void setEnterpriseid(String enterpriseid) {
    		this.enterpriseid = enterpriseid;
    	}

    	public String getLocaltax() {
    		return localtax;
    	}

    	public void setLocaltax(String localtax) {
    		this.localtax = localtax;
    	}

    	public String getModifyusername() {
    		return modifyusername;
    	}

    	public void setModifyusername(String modifyusername) {
    		this.modifyusername = modifyusername;
    	}

    	public String getStatetax() {
    		return statetax;
    	}

    	public void setStatetax(String statetax) {
    		this.statetax = statetax;
    	}

    	public String getTotleinput() {
    		return totleinput;
    	}

    	public void setTotleinput(String totleinput) {
    		this.totleinput = totleinput;
    	}

    	public String getTotleoutput() {
    		return totleoutput;
    	}

    	public void setTotleoutput(String totleoutput) {
    		this.totleoutput = totleoutput;
    	}

    	public Date getAddtime() {
    		return addtime;
    	}

    	public void setAddtime(Date addtime) {
    		this.addtime = addtime;
    	}

    	public Date getModifytime() {
    		return modifytime;
    	}

    	public void setModifytime(Date modifytime) {
    		this.modifytime = modifytime;
    	}

		public String getMarketrate() {
			return marketrate;
		}

		public void setMarketrate(String marketrate) {
			this.marketrate = marketrate;
		}

		public String getProfitrate() {
			return profitrate;
		}

		public void setProfitrate(String profitrate) {
			this.profitrate = profitrate;
		}

		public String getLocaltaxorg() {
			return localtaxorg;
		}

		public void setLocaltaxorg(String localtaxorg) {
			this.localtaxorg = localtaxorg;
		}

		public String getStatetaxorg() {
			return statetaxorg;
		}

		public void setStatetaxorg(String statetaxorg) {
			this.statetaxorg = statetaxorg;
		}

}
