package com.ikkong.system.model;

import java.math.BigDecimal;
import java.util.Date;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

/**
 * Generated by Blade.
 * 2017-12-05 21:40:33
 */
@Table(name = "glpt_enterprise_credit")
@BindID(name = "id")
@SuppressWarnings("serial")
public class EnterpriseCredit extends BaseModel {
    	private Long id;
    	private String adress; //地址
    	private String businessscope; //经营(业务)范围
    	private Long entid;
    	private String industrycategory; //行业门类
    	private BigDecimal lat; //维度
    	private String legalrepresentative; //法定代表人
    	private BigDecimal lng; //经度
    	private String name;
    	private BigDecimal registeredcapital; //注册资本
    	private String registrationauthority; //登记机关
    	private String registrationnumber; //工商注册号
    	private String socialcreditcode; //统一社会信用代码
    	private Date formatdate; //成立日期
    	private Date timelimitfrom; //经营期限自
    	private Date timelimitto; //经营期限至
    	private Date updatetime; //更新日期
    	private Integer areaid;//区域ID

    	@AutoID
    	public Long getId() {
    		return id;
    	}

    	public void setId(Long id) {
    		this.id = id;
    	}

    	public String getAdress() {
    		return adress;
    	}

    	public void setAdress(String adress) {
    		this.adress = adress;
    	}

    	public String getBusinessscope() {
    		return businessscope;
    	}

    	public void setBusinessscope(String businessscope) {
    		this.businessscope = businessscope;
    	}

    	public Long getEntid() {
    		return entid;
    	}

    	public void setEntid(Long entid) {
    		this.entid = entid;
    	}

    	public String getIndustrycategory() {
    		return industrycategory;
    	}

    	public void setIndustrycategory(String industrycategory) {
    		this.industrycategory = industrycategory;
    	}

    	public BigDecimal getLat() {
    		return lat;
    	}

    	public void setLat(BigDecimal lat) {
    		this.lat = lat;
    	}

    	public String getLegalrepresentative() {
    		return legalrepresentative;
    	}

    	public void setLegalrepresentative(String legalrepresentative) {
    		this.legalrepresentative = legalrepresentative;
    	}

    	public BigDecimal getLng() {
    		return lng;
    	}

    	public void setLng(BigDecimal lng) {
    		this.lng = lng;
    	}

    	public String getName() {
    		return name;
    	}

    	public void setName(String name) {
    		this.name = name;
    	}

    	public BigDecimal getRegisteredcapital() {
    		return registeredcapital;
    	}

    	public void setRegisteredcapital(BigDecimal registeredcapital) {
    		this.registeredcapital = registeredcapital;
    	}

    	public String getRegistrationauthority() {
    		return registrationauthority;
    	}

    	public void setRegistrationauthority(String registrationauthority) {
    		this.registrationauthority = registrationauthority;
    	}

    	public String getRegistrationnumber() {
    		return registrationnumber;
    	}

    	public void setRegistrationnumber(String registrationnumber) {
    		this.registrationnumber = registrationnumber;
    	}

    	public String getSocialcreditcode() {
    		return socialcreditcode;
    	}

    	public void setSocialcreditcode(String socialcreditcode) {
    		this.socialcreditcode = socialcreditcode;
    	}

    	public Date getFormatdate() {
    		return formatdate;
    	}

    	public void setFormatdate(Date formatdate) {
    		this.formatdate = formatdate;
    	}

    	public Date getTimelimitfrom() {
    		return timelimitfrom;
    	}

    	public void setTimelimitfrom(Date timelimitfrom) {
    		this.timelimitfrom = timelimitfrom;
    	}

    	public Date getTimelimitto() {
    		return timelimitto;
    	}

    	public void setTimelimitto(Date timelimitto) {
    		this.timelimitto = timelimitto;
    	}

		public Date getUpdatetime() {
			return updatetime;
		}

		public void setUpdatetime(Date updatetime) {
			this.updatetime = updatetime;
		}

		/**
		 * 区域ID：-1 仓山区域外； 0 仓山区内； 其他 区域ID
		 * @return
		 */
		public Integer getAreaid() {
			return areaid;
		}

		public void setAreaid(Integer areaid) {
			this.areaid = areaid;
		}

}
