package com.ikkong.system.model;

import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

import java.math.BigDecimal;
import java.util.Date;

import org.beetl.sql.core.annotatoin.AutoID;
/**
 * Generated by Blade.
 * 2017-11-07 18:07:53
 */
@Table(name = "glpt_enterprise")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Enterprise extends BaseModel {
    	private Long id; //id
    	private Integer adduserid; //新增用户ID
    	private Integer employees; //职工人数
    	private Integer foreignemployees; //外籍员工人数
    	private Integer modifyuserid; //修改用户id
    	private Integer status; //状态
    	private Integer version=0;
    	private String address; //详细地址
    	private String addusername; //新增用户
    	private String areacovered; //占地面积（平方米）
    	private String builtuparea; //建筑面积（平方米）
    	private String businesslicense; //营业执照注册号（统一社会信息代码）
    	private String businesstype; //经营类型
    	private String capital; //注册资本（万元）
    	private String chargerphone; //财务负责人手机
    	private String chargertel; //财务负责人办公电话
    	private String chargerfax; //财务负责人办公电话
    	private String fax; //传真
    	private String financialcharger; //财务负责人
    	private String ishightech; //高新技术企业（是否）
    	private String ldleworkshop; //闲置厂房/用地
    	private String legalperson;
    	private String linkername; //联系人姓名
    	private String linkerphone; //联系人手机
    	private String linkertel; //联系人办公电话
    	private String linkerfax; //联系人chuanz
    	
    	private String loansituation; //贷款情况
    	private String localtaxorg; //地税登记机关
    	private String lpintroduce; //法人简介
    	private String maill; //企业邮箱
    	private String modifyusername; //修改用户
    	private String name; //企业名称
    	private String officerphone; //安全负责人手机
    	private String officertel; //安全负责人办公电话
    	private String officerfax; //安全负责人办公电话
    	private String orgcode; //组织机构代码证
    	private String ownershiptype; //厂房归属（自建或租用）
    	private String phone; //联系电话
    	private String postalcode; //邮政编码
    	private String premarketrate; //上年度主要产品市场占有率
    	private String preprofitrate; //上年度企业利润率
    	private String profile; //企业简介
    	private String registtype; //登记注册类型
    	private String relocatetype; //企业搬迁意愿
    	private String safetyofficer; //安全负责人
    	private String safetyproduct; //安全生产标准化开展情况
    	private String statetaxorg; //国税登记机关
    	private String supply; //厂房供求情况
    	private String supporting; //需扶持事项
    	private String taxpayerNO; //企业纳税人识别号
    	private String techcentertype; //企业技术中心（国家/省/市）
    	private String violationsituation; //业主企业违章情况
    	private Date addtime; //新增时间
    	private Date formingtime; //成立时间
    	private Date modifytime; //修改时间

    	private Integer grider;//网格员
    	private Integer category;//企业类型
    	private Integer isowner;//是否业主
    	private String buildingid; //大楼ID，多个用逗号隔开
    	

    	private BigDecimal latitude; //纬度
    	private BigDecimal longitude; //经度
    	

    	private Integer outregist;//注册地类型：1园区内注册、2园区外注册、3仓山区外注册
    	private String registaddress; //注册地
    	private Date checkdate; //注册类型预计时间
    	private Integer checkstatus; //注册预警状态：1 预警中，0 已确认

    	@AutoID
    	public Long getId() {
    		return id;
    	}

    	public void setId(Long id) {
    		this.id = id;
    	}

    	public Integer getAdduserid() {
    		return adduserid;
    	}

    	public void setAdduserid(Integer adduserid) {
    		this.adduserid = adduserid;
    	}

    	public Integer getEmployees() {
    		return employees;
    	}

    	public void setEmployees(Integer employees) {
    		this.employees = employees;
    	}

    	public Integer getForeignemployees() {
    		return foreignemployees;
    	}

    	public void setForeignemployees(Integer foreignemployees) {
    		this.foreignemployees = foreignemployees;
    	}

    	public Integer getModifyuserid() {
    		return modifyuserid;
    	}

    	public void setModifyuserid(Integer modifyuserid) {
    		this.modifyuserid = modifyuserid;
    	}

    	public Integer getStatus() {
    		return status;
    	}

    	public void setStatus(Integer status) {
    		this.status = status;
    	}

    	public Integer getVersion() {
    		return version;
    	}

    	public void setVersion(Integer version) {
    		this.version = version;
    	}

    	public String getAddress() {
    		return address;
    	}

    	public void setAddress(String address) {
    		this.address = address;
    	}

    	public String getAddusername() {
    		return addusername;
    	}

    	public void setAddusername(String addusername) {
    		this.addusername = addusername;
    	}

    	public String getAreacovered() {
    		return areacovered;
    	}

    	public void setAreacovered(String areacovered) {
    		this.areacovered = areacovered;
    	}

    	public String getBuiltuparea() {
    		return builtuparea;
    	}

    	public void setBuiltuparea(String builtuparea) {
    		this.builtuparea = builtuparea;
    	}

    	public String getBusinesslicense() {
    		return businesslicense;
    	}

    	public void setBusinesslicense(String businesslicense) {
    		this.businesslicense = businesslicense;
    	}

    	public String getBusinesstype() {
    		return businesstype;
    	}

    	public void setBusinesstype(String businesstype) {
    		this.businesstype = businesstype;
    	}

    	public String getCapital() {
    		return capital;
    	}

    	public void setCapital(String capital) {
    		this.capital = capital;
    	}

    	public String getChargerphone() {
    		return chargerphone;
    	}

    	public void setChargerphone(String chargerphone) {
    		this.chargerphone = chargerphone;
    	}

    	public String getChargertel() {
    		return chargertel;
    	}

    	public void setChargertel(String chargertel) {
    		this.chargertel = chargertel;
    	}

    	public String getFax() {
    		return fax;
    	}

    	public void setFax(String fax) {
    		this.fax = fax;
    	}

    	public String getFinancialcharger() {
    		return financialcharger;
    	}

    	public void setFinancialcharger(String financialcharger) {
    		this.financialcharger = financialcharger;
    	}

    	public String getIshightech() {
    		return ishightech;
    	}

    	public void setIshightech(String ishightech) {
    		this.ishightech = ishightech;
    	}

    	public String getLdleworkshop() {
    		return ldleworkshop;
    	}

    	public void setLdleworkshop(String ldleworkshop) {
    		this.ldleworkshop = ldleworkshop;
    	}

    	public String getLegalperson() {
    		return legalperson;
    	}

    	public void setLegalperson(String legalperson) {
    		this.legalperson = legalperson;
    	}

    	public String getLinkername() {
    		return linkername;
    	}

    	public void setLinkername(String linkername) {
    		this.linkername = linkername;
    	}

    	public String getLinkerphone() {
    		return linkerphone;
    	}

    	public void setLinkerphone(String linkerphone) {
    		this.linkerphone = linkerphone;
    	}

    	public String getLinkertel() {
    		return linkertel;
    	}

    	public void setLinkertel(String linkertel) {
    		this.linkertel = linkertel;
    	}

    	public String getLoansituation() {
    		return loansituation;
    	}

    	public void setLoansituation(String loansituation) {
    		this.loansituation = loansituation;
    	}

    	public String getLocaltaxorg() {
    		return localtaxorg;
    	}

    	public void setLocaltaxorg(String localtaxorg) {
    		this.localtaxorg = localtaxorg;
    	}

    	public String getLpintroduce() {
    		return lpintroduce;
    	}

    	public void setLpintroduce(String lpintroduce) {
    		this.lpintroduce = lpintroduce;
    	}

    	public String getMaill() {
    		return maill;
    	}

    	public void setMaill(String maill) {
    		this.maill = maill;
    	}

    	public String getModifyusername() {
    		return modifyusername;
    	}

    	public void setModifyusername(String modifyusername) {
    		this.modifyusername = modifyusername;
    	}

    	public String getName() {
    		return name;
    	}

    	public void setName(String name) {
    		this.name = name;
    	}

    	public String getOfficerphone() {
    		return officerphone;
    	}

    	public void setOfficerphone(String officerphone) {
    		this.officerphone = officerphone;
    	}

    	public String getOfficertel() {
    		return officertel;
    	}

    	public void setOfficertel(String officertel) {
    		this.officertel = officertel;
    	}

    	public String getOrgcode() {
    		return orgcode;
    	}

    	public void setOrgcode(String orgcode) {
    		this.orgcode = orgcode;
    	}

    	public String getOwnershiptype() {
    		return ownershiptype;
    	}

    	public void setOwnershiptype(String ownershiptype) {
    		this.ownershiptype = ownershiptype;
    	}

    	public String getPhone() {
    		return phone;
    	}

    	public void setPhone(String phone) {
    		this.phone = phone;
    	}

    	public String getPostalcode() {
    		return postalcode;
    	}

    	public void setPostalcode(String postalcode) {
    		this.postalcode = postalcode;
    	}

    	public String getPremarketrate() {
    		return premarketrate;
    	}

    	public void setPremarketrate(String premarketrate) {
    		this.premarketrate = premarketrate;
    	}

    	public String getPreprofitrate() {
    		return preprofitrate;
    	}

    	public void setPreprofitrate(String preprofitrate) {
    		this.preprofitrate = preprofitrate;
    	}

    	public String getProfile() {
    		return profile;
    	}

    	public void setProfile(String profile) {
    		this.profile = profile;
    	}

    	public String getRegisttype() {
    		return registtype;
    	}

    	public void setRegisttype(String registtype) {
    		this.registtype = registtype;
    	}

    	public String getRelocatetype() {
    		return relocatetype;
    	}

    	public void setRelocatetype(String relocatetype) {
    		this.relocatetype = relocatetype;
    	}

    	public String getSafetyofficer() {
    		return safetyofficer;
    	}

    	public void setSafetyofficer(String safetyofficer) {
    		this.safetyofficer = safetyofficer;
    	}

    	public String getSafetyproduct() {
    		return safetyproduct;
    	}

    	public void setSafetyproduct(String safetyproduct) {
    		this.safetyproduct = safetyproduct;
    	}

    	public String getStatetaxorg() {
    		return statetaxorg;
    	}

    	public void setStatetaxorg(String statetaxorg) {
    		this.statetaxorg = statetaxorg;
    	}

    	public String getSupply() {
    		return supply;
    	}

    	public void setSupply(String supply) {
    		this.supply = supply;
    	}

    	public String getSupporting() {
    		return supporting;
    	}

    	public void setSupporting(String supporting) {
    		this.supporting = supporting;
    	}

    	public String getTaxpayerNO() {
    		return taxpayerNO;
    	}

    	public void setTaxpayerNO(String taxpayerNO) {
    		this.taxpayerNO = taxpayerNO;
    	}

    	public String getTechcentertype() {
    		return techcentertype;
    	}

    	public void setTechcentertype(String techcentertype) {
    		this.techcentertype = techcentertype;
    	}

    	public String getViolationsituation() {
    		return violationsituation;
    	}

    	public void setViolationsituation(String violationsituation) {
    		this.violationsituation = violationsituation;
    	}

    	public Date getAddtime() {
    		return addtime;
    	}

    	public void setAddtime(Date addtime) {
    		this.addtime = addtime;
    	}

    	public Date getFormingtime() {
    		return formingtime;
    	}

    	public void setFormingtime(Date formingtime) {
    		this.formingtime = formingtime;
    	}

    	public Date getModifytime() {
    		return modifytime;
    	}

    	public void setModifytime(Date modifytime) {
    		this.modifytime = modifytime;
    	}

		public String getChargerfax() {
			return chargerfax;
		}

		public void setChargerfax(String chargerfax) {
			this.chargerfax = chargerfax;
		}

		public String getLinkerfax() {
			return linkerfax;
		}

		public void setLinkerfax(String linkerfax) {
			this.linkerfax = linkerfax;
		}

		public String getOfficerfax() {
			return officerfax;
		}

		public void setOfficerfax(String officerfax) {
			this.officerfax = officerfax;
		}

		public Integer getGrider() {
			return grider;
		}

		public void setGrider(Integer grider) {
			this.grider = grider;
		}

		public Integer getCategory() {
			return category;
		}

		public void setCategory(Integer category) {
			this.category = category;
		}

		public Integer getIsowner() {
			return isowner;
		}

		public void setIsowner(Integer isowner) {
			this.isowner = isowner;
		}


		public String getBuildingid() {
			return buildingid;
		}

		public void setBuildingid(String buildingid) {
			this.buildingid = buildingid;
		}

		public BigDecimal getLatitude() {
			return latitude;
		}

		public void setLatitude(BigDecimal latitude) {
			this.latitude = latitude;
		}

		public BigDecimal getLongitude() {
			return longitude;
		}

		public void setLongitude(BigDecimal longitude) {
			this.longitude = longitude;
		}

		public Integer getOutregist() {
			return outregist;
		}

		public void setOutregist(Integer outregist) {
			this.outregist = outregist;
		}

		public String getRegistaddress() {
			return registaddress;
		}

		public void setRegistaddress(String registaddress) {
			this.registaddress = registaddress;
		}

		public Date getCheckdate() {
			return checkdate;
		}

		public void setCheckdate(Date checkdate) {
			this.checkdate = checkdate;
		}

		public Integer getCheckstatus() {
			return checkstatus;
		}

		public void setCheckstatus(Integer checkstatus) {
			this.checkstatus = checkstatus;
		}

}
