package com.ikkong.system.model;

import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

import java.math.BigDecimal;
import java.util.Date;

import org.beetl.sql.core.annotatoin.AutoID;
/**
 * Generated by Blade.
 * 2017-11-07 18:07:54
 */
@Table(name = "glpt_work_feedcontent")
@BindID(name = "id")
@SuppressWarnings("serial")
public class WorkFeedcontent extends BaseModel {
    	private Integer id; //ID
    	private Integer isfinish; //是否已结束
    	private Integer userid; //反馈人员
    	private Integer version=0;
    	private String feedcontent; //反馈内容
    	private String username; //反馈人员名称
    	private Long workid; //任务id
    	private Date feekbacktime; //反馈时间

    	@AutoID
    	public Integer getId() {
    		return id;
    	}

    	public void setId(Integer id) {
    		this.id = id;
    	}

    	public Integer getIsfinish() {
    		return isfinish;
    	}

    	public void setIsfinish(Integer isfinish) {
    		this.isfinish = isfinish;
    	}

    	public Integer getUserid() {
    		return userid;
    	}

    	public void setUserid(Integer userid) {
    		this.userid = userid;
    	}

    	public Integer getVersion() {
    		return version;
    	}

    	public void setVersion(Integer version) {
    		this.version = version;
    	}

    	public String getFeedcontent() {
    		return feedcontent;
    	}

    	public void setFeedcontent(String feedcontent) {
    		this.feedcontent = feedcontent;
    	}

    	public String getUsername() {
    		return username;
    	}

    	public void setUsername(String username) {
    		this.username = username;
    	}

    	public Long getWorkid() {
    		return workid;
    	}

    	public void setWorkid(Long workid) {
    		this.workid = workid;
    	}

    	public Date getFeekbacktime() {
    		return feekbacktime;
    	}

    	public void setFeekbacktime(Date feekbacktime) {
    		this.feekbacktime = feekbacktime;
    	}

}
