package com.ikkong.system.model;

import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

import java.math.BigDecimal;
import java.util.Date;

import org.beetl.sql.core.annotatoin.AutoID;
/**
 * Generated by Blade.
 * 2017-11-07 18:07:54
 */
@Table(name = "glpt_work_feedback")
@BindID(name = "id")
@SuppressWarnings("serial")
public class WorkFeedback extends BaseModel {
    	private Long id; //ID
    	private Integer isfinish; //是否已结束
    	private Integer version=0;
    	private String feedcontent; //反馈内容
    	private Integer userid;//接收人员id
    	private String username; //接收人员姓名
    	private Long workid; //任务id
    	private Date feekbacktime; //反馈时间
    	private Date readtime; //接收时间
    	private Integer status;//0 未读；1已读；2已反馈
    	private Date publishtime;

    	@AutoID
    	public Long getId() {
    		return id;
    	}

    	public void setId(Long id) {
    		this.id = id;
    	}

    	public Integer getIsfinish() {
    		return isfinish;
    	}

    	public void setIsfinish(Integer isfinish) {
    		this.isfinish = isfinish;
    	}

    	public Integer getVersion() {
    		return version;
    	}

    	public void setVersion(Integer version) {
    		this.version = version;
    	}

    	public String getFeedcontent() {
    		return feedcontent;
    	}

    	public void setFeedcontent(String feedcontent) {
    		this.feedcontent = feedcontent;
    	}

    	public String getUsername() {
    		return username;
    	}

    	public void setUsername(String username) {
    		this.username = username;
    	}

    	public Long getWorkid() {
    		return workid;
    	}

    	public void setWorkid(Long workid) {
    		this.workid = workid;
    	}

    	public Date getFeekbacktime() {
    		return feekbacktime;
    	}

    	public void setFeekbacktime(Date feekbacktime) {
    		this.feekbacktime = feekbacktime;
    	}

    	public Date getReadtime() {
    		return readtime;
    	}

    	public void setReadtime(Date readtime) {
    		this.readtime = readtime;
    	}

		public Integer getUserid() {
			return userid;
		}

		public void setUserid(Integer userid) {
			this.userid = userid;
		}

		public Integer getStatus() {
			return status;
		}

		public void setStatus(Integer status) {
			this.status = status;
		}

		public Date getPublishtime() {
			return publishtime;
		}

		public void setPublishtime(Date publishtime) {
			this.publishtime = publishtime;
		}

}
