package com.ikkong.system.model;

import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

import java.math.BigDecimal;
import java.util.Date;

import org.beetl.sql.core.annotatoin.AutoID;
/**
 * Generated by Blade.
 * 2017-11-07 18:07:54
 */
@Table(name = "glpt_work")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Work extends BaseModel {
    	private Integer id; //ID
    	private Integer ismutil; //是否多人任务
    	private Integer status; //status
    	private Integer version=0;
    	private Long adduserid; //添加用户ID
    	private String addusername; //添加用户名
    	private String content; //任务内容
    	private String title; //任务标题
    	private Date addtime; //添加时间
    	private Date finishdate; //实际完成时间
    	private Date plantdate; //计划完成时间
    	private String reciveuserids;//任务接收人
    	private Date publishtime;

    	@AutoID
		public Integer getId() {
			return id;
		}

		public void setId(Integer id) {
			this.id = id;
		}

    	public Integer getIsmutil() {
    		return ismutil;
    	}

    	public void setIsmutil(Integer ismutil) {
    		this.ismutil = ismutil;
    	}

    	public Integer getStatus() {
    		return status;
    	}

    	public void setStatus(Integer status) {
    		this.status = status;
    	}

    	public Integer getVersion() {
    		return version;
    	}

    	public void setVersion(Integer version) {
    		this.version = version;
    	}

    	public Long getAdduserid() {
    		return adduserid;
    	}

    	public void setAdduserid(Long adduserid) {
    		this.adduserid = adduserid;
    	}

    	public String getAddusername() {
    		return addusername;
    	}

    	public void setAddusername(String addusername) {
    		this.addusername = addusername;
    	}

    	public String getContent() {
    		return content;
    	}

    	public void setContent(String content) {
    		this.content = content;
    	}

    	public String getTitle() {
    		return title;
    	}

    	public void setTitle(String title) {
    		this.title = title;
    	}

    	public Date getAddtime() {
    		return addtime;
    	}

    	public void setAddtime(Date addtime) {
    		this.addtime = addtime;
    	}

    	public Date getFinishdate() {
    		return finishdate;
    	}

    	public void setFinishdate(Date finishdate) {
    		this.finishdate = finishdate;
    	}

    	public Date getPlantdate() {
    		return plantdate;
    	}

    	public void setPlantdate(Date plantdate) {
    		this.plantdate = plantdate;
    	}

		public String getReciveuserids() {
			return reciveuserids;
		}

		public void setReciveuserids(String reciveuserids) {
			this.reciveuserids = reciveuserids;
		}

		public Date getPublishtime() {
			return publishtime;
		}

		public void setPublishtime(Date publishtime) {
			this.publishtime = publishtime;
		}


}
