package com.ikkong.vote.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.vote.model.Complaint;
import com.ikkong.vote.service.ComplaintService;

/**
 * Generated by Blade.
 * 2019-01-20 18:59:30
 */
public class ComplaintServiceImpl extends BaseService<Complaint> implements ComplaintService{

}
