package com.ikkong.vote.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.vote.model.Orders;
import com.ikkong.vote.service.OrdersService;

/**
 * Generated by Blade.
 * 2018-08-26 00:46:42
 */
public class OrdersServiceImpl extends BaseService<Orders> implements OrdersService{

}
