package com.ikkong.vote.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.core.dao.Db;
import com.ikkong.core.toolbox.Record;
import com.ikkong.core.toolbox.support.BladePage;
import com.ikkong.vote.model.Task;
import com.ikkong.vote.service.TaskService;

import java.util.List;

/**
 * Generated by Blade.
 * 2018-10-15 14:43:20
 */
public class TaskServiceImpl extends BaseService<Task> implements TaskService{

    @Override
    public List<Task> queryToDoList(Record record){
        return super.find(Db.init().getSql("Task.todolist"),record);
    }

    @Override
    public void  deleteTask(Record record){
        StringBuilder sql = new StringBuilder();
        if(record.get("eids")!=null) {
            sql.append(" delete from  t_task  " +
                    " where event_id in( #{text(eids)} );");
        }
        if(record.get("mids")!=null) {
            sql.append(" delete from  t_task  " +
                    " where merchantid in( #{text(mids)} );");
        }
        Db.init().update(sql.toString(), record);
    }



    @Override
    public void updateExec(Record record){
        StringBuilder sql = new StringBuilder();
        sql.append("update t_task" +
                " set exectime=#{exectime} " +
                " ,execbatchno=#{execbatchno} " +
                " where id=#{id}");
        Db.init().update(sql.toString(), record);
    }




}
