package com.ikkong.vote.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.vote.model.VoteUser;
import com.ikkong.vote.service.VoteUserService;

/**
 * Generated by Blade.
 * 2018-08-26 00:46:42
 */
public class VoteUserServiceImpl extends BaseService<VoteUser> implements VoteUserService{

}
