package com.ikkong.vote.service.impl;

import com.alibaba.druid.util.StringUtils;
import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.core.dao.Db;
import com.ikkong.core.toolbox.Record;
import com.ikkong.vote.model.VoteList;
import com.ikkong.vote.service.VoteListService;

import java.util.List;

/**
 * Generated by Blade.
 * 2018-08-26 00:46:42
 */
public class VoteListServiceImpl extends BaseService<VoteList> implements VoteListService {

    /**
     * 最新VIP投票
     *
     * @param record
     * @return
     */
    @Override
    public List<Record> querylastvipList(Record record) {
        String sql = Db.init().getSql("VoteList.lastvipList");
        return Db.init().selectList(sql, record);
    }

    /**
     * 查询金额
     *
     * @param record
     * @return
     */
    @Override
    public Double sumAmount(Record record) {
        String sql = Db.init().getSql("VoteList.sumAmount");
        String amount = Db.init().selectOne(sql, record).getStr("amount");
        if (StringUtils.isEmpty(amount)) {
            return 0D;
        }
        return Double.parseDouble(amount);
    }

    /**
     * 图表信息
     *
     * @param record
     * @return
     */
    @Override
    public List<Record> countInfo(Record record) {
        String sql = Db.init().getSql("VoteList.countInfo");
        return Db.init().selectList(sql, record);
    }

}
