package com.ikkong.vote.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.vote.model.Complaint;

/**
 * Generated by Blade.
 * 2019-01-20 18:59:30
 */
public interface ComplaintService extends IService<Complaint>{

}
