package com.ikkong.vote.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.core.toolbox.Record;
import com.ikkong.vote.model.Event;

/**
 * Generated by Blade.
 * 2018-08-26 00:46:42
 */
public interface EventService extends IService<Event>{


    public int deleteById(Record record);


    public void updateTicket( Record record);
    public void updateHits(Record record);
    public int recycleById(Record record);



    public int countEvent(Record record);



    public int updateVoteEndTimebyIds(Integer seconds,String ids);

}
