package com.ikkong.vote.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.core.toolbox.Record;
import com.ikkong.vote.model.Merchant;

import java.util.List;

/**
 * Generated by Blade.
 * 2018-08-26 00:46:42
 */
public interface MerchantService extends IService<Merchant>{

    public int deleteById(Record record) ;
    public int deleteByEventId(Record record) ;
    public List<Merchant> queryList( Record record);

    public void updateTicket( Record record);
    public void updateHits( Record record);

    public int recycleByEventId(Record record) ;

    public int recycleById(Record record) ;




}
