package com.ikkong.vote.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.vote.model.Orders;

/**
 * Generated by Blade.
 * 2018-08-26 00:46:42
 */
public interface OrdersService extends IService<Orders>{

}
