package com.ikkong.vote.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.core.toolbox.Record;
import com.ikkong.vote.model.Task;

import java.util.List;

/**
 * Generated by Blade.
 * 2018-10-15 14:43:20
 */
public interface TaskService extends IService<Task> {


    /**
     * 查询需要执行的任务
     * @param record
     * @return
     */
    public List<Task> queryToDoList(Record record);

    /**
     * 删除任务,根据选择的eids，mids
     * @param record
     */
    public void  deleteTask(Record record);


    public void updateExec(Record record);


}
