package com.ikkong.vote.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.vote.model.VoteUser;

/**
 * Generated by Blade.
 * 2018-08-26 00:46:42
 */
public interface VoteUserService extends IService<VoteUser>{

}
