package com.ikkong.vote.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.core.toolbox.Record;
import com.ikkong.vote.model.VoteList;

import java.util.List;

/**
 * Generated by Blade.
 * 2018-08-26 00:46:42
 */
public interface VoteListService extends IService<VoteList> {

    /**
     * 最新VIP投票
     * @param record
     * @return
     */
    public List<Record> querylastvipList(Record record);

    /**
     * 查询金额
     * @param record
     * @return
     */
    public Double sumAmount(Record record);

    /**
     *  图表信息
     * @param record
     * @return
     */
    public List<Record> countInfo(Record record);

}
