package com.ikkong.system.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.system.model.BuildingOwnerRel;

/**
 * Generated by Blade.
 * 2017-11-07 17:36:57
 */
public interface BuildingOwnerRelService extends IService<BuildingOwnerRel>{

}
