package com.ikkong.system.service;

import java.util.List;

import com.ikkong.core.base.service.IService;
import com.ikkong.core.toolbox.Record;
import com.ikkong.system.model.Building;

/**
 * Generated by Blade.
 * 2017-11-07 17:36:57
 */
public interface BuildingService extends IService<Building>{
	
	/**
	 * 查询片区内建筑数
	 * @param record
	 * @return
	 */
	public List<Record> queryBuildingList(Record record);
	/**
	 * 按第查询楼宇
	 * @param ids
	 * @return
	 */
	public List<Record> queryBuildingByIds(String ids);
	
	public int  mergeBuildingByIds(String ids, String id,String newName);
}
