package com.ikkong.system.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.system.model.BuildingOwner;

/**
 * Generated by Blade.
 * 2017-11-07 17:36:57
 */
public interface BuildingOwnerService extends IService<BuildingOwner>{

}
