package com.ikkong.system.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.system.model.EnterpriseCredit;

/**
 * Generated by Blade.
 * 2017-12-05 21:40:33
 */
public interface EnterpriseCreditService extends IService<EnterpriseCredit>{

}
