package com.ikkong.system.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.system.model.EnterprisesCertification;

/**
 * Generated by Blade.
 * 2017-11-07 17:36:57
 */
public interface EnterprisesCertificationService extends IService<EnterprisesCertification>{

}
