package com.ikkong.system.service;

import java.util.List;

import com.ikkong.core.base.service.IService;
import com.ikkong.system.model.Signin;
import com.ikkong.core.toolbox.Record;

/**
 * Generated by Blade.
 * 2017-11-07 17:36:57
 */
public interface SigninService extends IService<Signin>{

	public abstract List querySigninList(Record record);

	public abstract List queryByDeptAndDate(Record record);

	public abstract Object queryUserSigin(Record record, int i, int j);
}

