package com.ikkong.system.service;

import java.util.List;

import com.ikkong.core.base.service.IService;
import com.ikkong.system.model.WorkFeedback;

/**
 * Generated by Blade.
 * 2017-11-07 17:36:57
 */
public interface WorkFeedbackService extends IService<WorkFeedback>{
	public void saveWorkFeedbackList(List<WorkFeedback> list);
}
