package com.ikkong.system.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.system.model.Work;

/**
 * Generated by Blade.
 * 2017-11-07 17:36:57
 */
public interface WorkService extends IService<Work>{
	
	public String publishWork(Integer id);
	

}
