package com.ikkong.vote.model;

import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

import java.util.Date;

/**
 * Generated by Blade.
 * 2019-01-20 18:59:30
 */
@Table(name = "t_complaint")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Complaint extends BaseModel {
    	private Integer id;
    	private Integer eventid; //活动id
    	private Integer merchantid; //选手id
    	private String ctype; //投诉类型
    	private String openid; //用户ID
    	private Date createtime; //投诉时间


    	public Integer getId() {
    		return id;
    	}

    	public void setId(Integer id) {
    		this.id = id;
    	}

    	public Integer getEventid() {
    		return eventid;
    	}

    	public void setEventid(Integer eventid) {
    		this.eventid = eventid;
    	}

    	public Integer getMerchantid() {
    		return merchantid;
    	}

    	public void setMerchantid(Integer merchantid) {
    		this.merchantid = merchantid;
    	}

    	public String getCtype() {
    		return ctype;
    	}

    	public void setCtype(String ctype) {
    		this.ctype = ctype;
    	}

    	public String getOpenid() {
    		return openid;
    	}

    	public void setOpenid(String openid) {
    		this.openid = openid;
    	}

    	public Date getCreatetime() {
    		return createtime;
    	}

    	public void setCreatetime(Date createtime) {
    		this.createtime = createtime;
    	}

}
