package com.ikkong.vote.model;

import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

import java.util.Date;

/**
 * Generated by Blade.
 * 2018-08-26 00:46:42
 */
@Table(name = "t_event")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Event extends BaseModel {
    private Integer id;
    private Integer creatr_user_id; //创建用户ID
    private Integer hits; //人气数
    private Integer totlevotes; //总票数
    private Integer update_user_id; //修改用户ID
    private String vipenabled; //是否允许VIP投票
    private Integer viplimit; //Vip票每日限制
    private float vipprice; //VIP票单价
    private Integer vipvotes; //VIP票数
    private Integer votelimit; //每日普通票限制
    private String banner; //活动抬头轮播显示
    private String channeltype; //通道類型
    private String introduce; //活动介绍
    private String memo; //活动备注
    private String name; //id
    private String pictures; //活动图片
    private String prize; //活动奖品
    private String sharingintroduce; //分享介绍
    private String status; //状态
    private String tips; //活动提示
    private Date create_time;
    private Date joinbegintime; //活动报名开始时间
    private Date joinendtime; //活动报名结束时间
    private Date update_time;
    private Date votebegintime; //活动投票开始时间
    private Date voteendtime; //活动投票结束时间
    private Integer version;
    private String creatr_user_name;

    public String getCreatr_user_name() {
        return creatr_user_name;
    }

    public void setCreatr_user_name(String creatr_user_name) {
        this.creatr_user_name = creatr_user_name;
    }


    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCreatr_user_id() {
        return creatr_user_id;
    }

    public void setCreatr_user_id(Integer creatr_user_id) {
        this.creatr_user_id = creatr_user_id;
    }

    public Integer getHits() {
        return hits;
    }

    public void setHits(Integer hits) {
        this.hits = hits;
    }

    public Integer getTotlevotes() {
        return totlevotes;
    }

    public void setTotlevotes(Integer totlevotes) {
        this.totlevotes = totlevotes;
    }

    public Integer getUpdate_user_id() {
        return update_user_id;
    }

    public void setUpdate_user_id(Integer update_user_id) {
        this.update_user_id = update_user_id;
    }

    public String getVipenabled() {
        return vipenabled;
    }

    public void setVipenabled(String vipenabled) {
        this.vipenabled = vipenabled;
    }

    public Integer getViplimit() {
        return viplimit;
    }

    public void setViplimit(Integer viplimit) {
        this.viplimit = viplimit;
    }

    public float getVipprice() {
        return vipprice;
    }

    public void setVipprice(float vipprice) {
        this.vipprice = vipprice;
    }

    public Integer getVipvotes() {
        return vipvotes;
    }

    public void setVipvotes(Integer vipvotes) {
        this.vipvotes = vipvotes;
    }

    public Integer getVotelimit() {
        return votelimit;
    }

    public void setVotelimit(Integer votelimit) {
        this.votelimit = votelimit;
    }

    public String getBanner() {
        return banner;
    }

    public void setBanner(String banner) {
        this.banner = banner;
    }

    public String getChanneltype() {
        return channeltype;
    }

    public void setChanneltype(String channeltype) {
        this.channeltype = channeltype;
    }

    public String getIntroduce() {
        return introduce;
    }

    public void setIntroduce(String introduce) {
        this.introduce = introduce;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPictures() {
        return pictures;
    }

    public void setPictures(String pictures) {
        this.pictures = pictures;
    }

    public String getPrize() {
        return prize;
    }

    public void setPrize(String prize) {
        this.prize = prize;
    }

    public String getSharingintroduce() {
        return sharingintroduce;
    }

    public void setSharingintroduce(String sharingintroduce) {
        this.sharingintroduce = sharingintroduce;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getTips() {
        return tips;
    }

    public void setTips(String tips) {
        this.tips = tips;
    }

    public Date getCreate_time() {
        return create_time;
    }

    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    public Date getJoinbegintime() {
        return joinbegintime;
    }

    public void setJoinbegintime(Date joinbegintime) {
        this.joinbegintime = joinbegintime;
    }

    public Date getJoinendtime() {
        return joinendtime;
    }

    public void setJoinendtime(Date joinendtime) {
        this.joinendtime = joinendtime;
    }

    public Date getUpdate_time() {
        return update_time;
    }

    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    public Date getVotebegintime() {
        return votebegintime;
    }

    public void setVotebegintime(Date votebegintime) {
        this.votebegintime = votebegintime;
    }

    public Date getVoteendtime() {
        return voteendtime;
    }

    public void setVoteendtime(Date voteendtime) {
        this.voteendtime = voteendtime;
    }

}
