package com.ikkong.vote.model;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

import java.util.Date;

/**
 * Generated by Blade.
 * 2018-10-15 14:43:20
 */
@Table(name = "t_task")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Task extends BaseModel {
    private Integer id;
    private Integer creatruserid; //添加用户ID
    private Integer event_id; //活动ID
    private Integer interval; //修改间隔
    private Integer maxvalue; //最高值
    private Integer merchantid; //选手ID
    private Integer minvalue; //最低值
    private Integer status; //状态:1生效、0 失效
    private Date createtime;
    private Date endtime; //结束时间
    private Date starttime; //开始时间
    private Integer version;//版本号
    private Date exectime;
    private String execexecbatchno;

    public String getExecexecbatchno() {
        return execexecbatchno;
    }

    public String setExecexecbatchno(String execexecbatchno) {
        return this.execexecbatchno = execexecbatchno;
    }

    public Date getExectime() {
        return exectime;
    }

    public void setExectime(Date exectime) {
        this.exectime = exectime;
    }


    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @AutoID
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCreatruserid() {
        return creatruserid;
    }

    public void setCreatruserid(Integer creatruserid) {
        this.creatruserid = creatruserid;
    }

    public Integer getEvent_id() {
        return event_id;
    }

    public void setEvent_id(Integer event_id) {
        this.event_id = event_id;
    }

    public Integer getInterval() {
        return interval;
    }

    public void setInterval(Integer interval) {
        this.interval = interval;
    }

    public Integer getMaxvalue() {
        return maxvalue;
    }

    public void setMaxvalue(Integer maxvalue) {
        this.maxvalue = maxvalue;
    }

    public Integer getMerchantid() {
        return merchantid;
    }

    public void setMerchantid(Integer merchantid) {
        this.merchantid = merchantid;
    }

    public Integer getMinvalue() {
        return minvalue;
    }

    public void setMinvalue(Integer minvalue) {
        this.minvalue = minvalue;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Date getCreatetime() {
        return createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    public Date getEndtime() {
        return endtime;
    }

    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    public Date getStarttime() {
        return starttime;
    }

    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

}
