package com.ikkong.vote.model;

import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

import java.util.Date;

/**
 * Generated by Blade.
 * 2018-08-26 00:46:42
 */
@Table(name = "t_vote_list")
@BindID(name = "id")
@SuppressWarnings("serial")
public class VoteList extends BaseModel {
    private Integer id;
    private Integer eventid; //活动ID
    private Integer merchantid; //选手ID
    private Integer orderid; //VIP投票的订单ID
    private Integer votetype; //投票类型：普通、VIP
    private String openid; //绑定的微信公众号OPENID
    private String status; //状态：已生效、未支付、支付成功
    private Integer tickets; //
    private Date update_time;
    private Date vote_time;
    private Integer version;



    public Integer getTickets() {
        return tickets;
    }

    public void setTickets(Integer tickets) {
        this.tickets = tickets;
    }


    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getEventid() {
        return eventid;
    }

    public void setEventid(Integer eventid) {
        this.eventid = eventid;
    }

    public Integer getMerchantid() {
        return merchantid;
    }

    public void setMerchantid(Integer merchantid) {
        this.merchantid = merchantid;
    }

    public Integer getOrderid() {
        return orderid;
    }

    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    public Integer getVotetype() {
        return votetype;
    }

    public void setVotetype(Integer votetype) {
        this.votetype = votetype;
    }

    public String getOpenid() {
        return openid;
    }

    public void setOpenid(String openid) {
        this.openid = openid;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getUpdate_time() {
        return update_time;
    }

    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    public Date getVote_time() {
        return vote_time;
    }

    public void setVote_time(Date vote_time) {
        this.vote_time = vote_time;
    }

}
