package com.ikkong.system.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.system.model.BuildingOwnerRel;
import com.ikkong.system.service.BuildingOwnerRelService;

/**
 * Generated by Blade.
 * 2017-11-07 17:36:57
 */
public class BuildingOwnerRelServiceImpl extends BaseService<BuildingOwnerRel> implements BuildingOwnerRelService{

}
