package com.ikkong.system.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.system.model.BuildingOwner;
import com.ikkong.system.service.BuildingOwnerService;

/**
 * Generated by Blade.
 * 2017-11-07 17:36:57
 */
public class BuildingOwnerServiceImpl extends BaseService<BuildingOwner> implements BuildingOwnerService{

}
