package com.ikkong.system.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.system.model.EnterprisesCertification;
import com.ikkong.system.service.EnterprisesCertificationService;

/**
 * Generated by Blade.
 * 2017-11-07 17:36:57
 */
public class EnterprisesCertificationServiceImpl extends BaseService<EnterprisesCertification> implements EnterprisesCertificationService{

}
