package com.ikkong.system.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.system.model.EnterprisesHolders;
import com.ikkong.system.service.EnterprisesHoldersService;

/**
 * Generated by Blade.
 * 2017-11-07 17:36:57
 */
public class EnterprisesHoldersServiceImpl extends BaseService<EnterprisesHolders> implements EnterprisesHoldersService{

}
