package com.ikkong.system.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.system.model.EnterpriseProduct;
import com.ikkong.system.service.EnterpriseProductService;

/**
 * Generated by Blade.
 * 2017-11-07 17:36:57
 */
public class EnterpriseProductServiceImpl extends BaseService<EnterpriseProduct> implements EnterpriseProductService{

}
