package com.ikkong.system.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.system.model.EnterpriseCredit;
import com.ikkong.system.service.EnterpriseCreditService;

/**
 * Generated by Blade.
 * 2017-12-05 21:40:33
 */
public class EnterpriseCreditServiceImpl extends BaseService<EnterpriseCredit> implements EnterpriseCreditService{

}
