package com.ikkong.system.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.system.model.EnterpriseBuildRel;
import com.ikkong.system.service.EnterpriseBuildRelService;

/**
 * Generated by Blade.
 * 2017-11-07 17:36:57
 */
public class EnterpriseBuildRelServiceImpl extends BaseService<EnterpriseBuildRel> implements EnterpriseBuildRelService{

}
