package com.ikkong.system.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.system.model.EnterprisesManagement;
import com.ikkong.system.service.EnterprisesManagementService;

/**
 * Generated by Blade.
 * 2017-11-07 17:36:57
 */
public class EnterprisesManagementServiceImpl extends BaseService<EnterprisesManagement> implements EnterprisesManagementService{

}
