package com.ikkong.system.service.impl;

import java.util.Date;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.core.dao.Db;
import com.ikkong.core.toolbox.Record;
import com.ikkong.system.model.Work;
import com.ikkong.system.model.WorkFeedback;
import com.ikkong.system.service.WorkService;

/**
 * Generated by Blade.
 * 2017-11-07 17:36:57
 */
public class WorkServiceImpl extends BaseService<Work> implements WorkService{

	@Override
	public String publishWork(Integer id) {
		Work work=super.findById(id);
		if(1!=work.getStatus())		{
			return "已发布任务不可重复发布";
		}
		work.setStatus(2);
		work.setVersion(work.getVersion()+1);
		work.setPublishtime(new Date());
		super.update(work);
		
		Db dao = Db.init();
//		String countSql="select count(0) as num from glpt_work_feedback where workid="+id;
//		Record record=dao.selectOne(countSql);
//		if(record.containsKey("num")&&record.getInt("num")==0){
//			return "任务为配置接收人员，不可发布";
//		}
		
		dao.deleteByIds("glpt_work_feedback", "workid", id.toString());
		
		String insertSql="  insert into glpt_work_feedback(workid,userid,username,status,publishtime)"
				+ " select w.ID,u.id,u.`NAME`,0,now()"
				+ " from glpt_work w"
				+ " join tfw_user u on find_in_set(u.id,w.reciveuserids)>0"
				+ " where w.id="+id;
		dao.update(insertSql , null);
		return "";
	}

}
