package com.ikkong.system.service.impl;

import java.util.List;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.system.model.WorkFeedback;
import com.ikkong.system.service.WorkFeedbackService;

/**
 * Generated by Blade.
 * 2017-11-07 17:36:57
 */
public class WorkFeedbackServiceImpl extends BaseService<WorkFeedback> implements WorkFeedbackService{

	@Override
	public void saveWorkFeedbackList(List<WorkFeedback> list) {
		for(WorkFeedback record:list){
			super.save(record);
		}
	}

}
