package com.ikkong.system.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.system.model.WorkFeedcontent;
import com.ikkong.system.service.WorkFeedcontentService;

/**
 * Generated by Blade.
 * 2017-11-07 17:36:57
 */
public class WorkFeedcontentServiceImpl extends BaseService<WorkFeedcontent> implements WorkFeedcontentService{

}
