package com.ikkong.vote.controller;

import com.ikkong.core.base.BaseController;
import com.ikkong.core.jfinal.ext.kit.JsonKit;
import com.ikkong.core.toolbox.Record;
import com.ikkong.vote.model.Event;
import com.ikkong.vote.service.EventService;
import com.ikkong.vote.service.MerchantService;
import com.ikkong.vote.service.impl.EventServiceImpl;
import com.ikkong.vote.service.impl.MerchantServiceImpl;
import org.apache.commons.lang3.StringUtils;

import java.io.UnsupportedEncodingException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/**
 * Generated by Blade.
 * 2016-10-08 15:59:45
 */
public class StatisticsController extends BaseController {
    private static String CODE = "statistics";
    private static String PERFIX = "event";
    private static String LIST_SOURCE = "Event.eventstatistics";
    private static String BASE_PATH = "/eventstatistics/";

    EventService service = new EventServiceImpl();


    public void index() {
        setAttr("code", CODE);
        Date today=new Date();
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        setAttr("enddate",sdf.format(today));

        Calendar calendar=Calendar.getInstance();
        calendar.setTime(today);
        calendar.add(Calendar.DATE,-7);
        setAttr("begindate",sdf.format(calendar.getTime()));

        render(BASE_PATH + "event.html");
    }


    public void list() {
        Record record = Record.create();
        if(!isStatistics()) {
            record.set("deptid", getDeptId());
        }
        String status = getPara("status", "1");
        String startDate = getPara("startDate");
        String endDate = getPara("endDate");
        record.set("status", status);
        record.set("startDate", startDate);
        record.set("endDate", endDate);

        String sidx = getPara("sidx", "");
        String sord = getPara("sord", "");
        record.set("sortfield",sidx);
        record.set("sortDirection",sord);

        Object grid = paginate(LIST_SOURCE, record);
        renderJson(grid);
    }





}
