package com.ikkong.vote.controller;

import com.ikkong.core.base.BaseController;
import com.ikkong.core.jfinal.ext.kit.JsonKit;
import com.ikkong.core.toolbox.Record;
import com.ikkong.system.controller.base.UrlPermissController;
import com.ikkong.vote.service.VoteListService;
import com.ikkong.vote.service.impl.VoteListServiceImpl;

/**
 * Generated by Blade.
 * 2016-10-08 15:59:45
 */
public class VoteController extends BaseController {
    private static String CODE = "vote";
    private static String PERFIX = "vote";
    private static String LIST_SOURCE = "VoteList.list";
    private static String BASE_PATH = "/vote/";

    VoteListService service = new VoteListServiceImpl();


    public void index() {
        setAttr("code", CODE);
        Object grid = getPage();
        setAttr("grid", grid);
        render(BASE_PATH + "list.html");
    }


    /**
     * 取分页内容
     */
    public void page() {
        Object grid = getPage();
        setAttr("grid", grid);
        render(BASE_PATH + "table.html");
    }

    /**
     * 分页取数据
     *
     * @return
     */
    private Object getPage() {
        Record record = Record.create();
        if(!isAdmin()) {
            record.set("deptid", getDeptId());
        }
        String eventid = getPara("eventid", "");
        setAttr("eventid", eventid);
        record.set("eventid", eventid);
        String mid = getPara("mid", "");
        setAttr("mid", mid);
        record.set("mid", mid);
        String status = getPara("status", "1");
        String keystr = getPara("keystr", "");
        if (!"0".equals(status)) {
            if("1".equals(status)){
                record.set("votetype", 2);
            }else {
                record.set("status", status);
            }
        }
        record.set("keystr", keystr);
        return paginate(LIST_SOURCE, record);
    }

}
